### ISSUE TITLE
使用GridLayoutManager再添加HeadView 第一行的spanSize会失效

### ISSUE THREAD

**Issue by zhengxuan666** [crazysunj/MultiTypeRecyclerViewAdapter#1]
我大概是这么判断的
final GridLayoutManager layoutManager = new GridLayoutManager(getContext(), 2, GridLayoutManager.VERTICAL, false);
layoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                MutiTypeTitleEntity entity=adapter.getItem(position);
                if (entity instanceof ItemEntity1){
                    return 1;
                }
                return layoutManager.getSpanCount();
        });

在未给RecycleView添加HeadView的情况下分类的头能占满一行,但是添加了headview 第一个类型的标题就会和内容挤在一起

**Comment by crazysunj** [comment]
你好，库的版本和具体异常信息，还有你得headView是指单个type的还是整个列表的？应该是没适配内外position，可以加我QQ387953660细聊，这个来回不太方便。

**Comment by zhengxuan666** [comment]
已经申请好友了我QQ是307778252

**Comment by zhengxuan666** [comment]
感谢解答
        layoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {

            @Override
            public int getSpanSize(int position) {
                if (position == 0) return 2;
                int itemType = helper.getItemViewType(position-1);
                if (itemType == 0) {
                    return 1;
                }
                return layoutManager.getSpanCount();
      }
        });
这样调整之后解决了问题。
