### ISSUE TITLE
关于分组的实现

### ISSUE THREAD

**Issue by yihuajia** [crazysunj/MultiTypeRecyclerViewAdapter#11]
你好，请问下如果需要分组的话是得注册多个level?使用sticky必须得设置header对吗？

**Comment by crazysunj** [comment]
你好，sticky并不是框架的东西，这只是体现扩展性高，demo中sticky只要是相同的headerId，就会分到一组（连续的）

**Comment by yihuajia** [comment]
好的，已经处理了。我关了
