### ISSUE TITLE
使用成本较高

### ISSUE THREAD

**Issue by fg2q1q3q** [crazysunj/MultiTypeRecyclerViewAdapter#12]
老实说，这个库应该可能比较优秀，但是光看使用说明书就感觉接入成本很高，要自己写不少文件，我只是需要一个类似ExpandableGridview的效果，能折叠，能设置列数，不卡顿，支持单数据刷新。找到这个库希望快速接入并修改成我自己想要的效果，结果发现需要处理的东西实在不少，而且貌似不支持动态设置level（可能没看完整）
作为一个库而言，需要用户关注的其实是配置，门槛尽可能低，实在没法低就搭个常用的台阶，比如实现常用的helper而不是作为例子仅供参考。建议未必合理，只是随口发发牢骚

**Comment by crazysunj** [comment]
你好，谢谢你的意见，但这个库并不是去实现ExpandableGridview的效果，它单纯只是在数据上的处理，属于轻量级框架，比较像ExpandableGridview这种情况需要自己封装；比较实现一个下拉刷新这种都是需要二次封装，这些都是UI的逻辑，库只关注数据的处理，让开发者更好去关注UI逻辑。现在暂时不支持动态level。但从数据处理来看，接入成本是极低的。ExpandableGridview实现并不是很复杂，可以说很简单，在我另一个开源项目crazydaily里面的联系人模块就有实现。

**Comment by hiliving** [comment]
话说我也有同感，乍一看确实理解费力，光是照葫芦画瓢就拷贝了一堆代码，可能是我比较菜，没花时间去理解吧，看起来是挺强大的
