### ISSUE TITLE
App 那个测试例子用不了吗！

### ISSUE THREAD

**Issue by ousq** [crazysunj/MultiTypeRecyclerViewAdapter#13]
AptDefaultHelperAdapterHelper 提示找不到这个类

**Comment by crazysunj** [comment]
你看看你gradle配置是否都支持

**Comment by ousq** [comment]
As 是用的最新版本

**Comment by ousq** [comment]
sample 可以用  就行想看看app的其他例子

**Comment by ousq** [comment]
![image](https://user-images.githubusercontent.com/18591884/60405661-3543df00-9be4-11e9-9b8c-79ba0680c058.png)
其他配置没有找到这个类
