### ISSUE TITLE
某个item中可能有几种布局,可以支持吗?

### ISSUE THREAD

**Issue by LouisMari1991** [crazysunj/MultiTypeRecyclerViewAdapter#3]
比如一个 RecyclerView 中包含 新闻, 购物 等几种 itemType, 
然后在 新闻 item 中又会包含几种布局的类型(layout),  购物 item 中也会包含几种布局的类型(layout);
看示例代码中同一个item 中可以设置 head, content, foot 的布局文件,  content 中可以再设置几个 layout 吗?

**Comment by crazysunj** [comment]
可以加我QQ387953660具体讨论

**Comment by OliverY** [comment]
想问问这个需求后来是怎么解决的
