### ISSUE TITLE
看了使用说明书，更使用不来了。用隔壁的了。

### ISSUE THREAD

**Issue by xianjiajun** [crazysunj/MultiTypeRecyclerViewAdapter#4]
rt

**Comment by crazysunj** [comment]
可以看看demo的使用（三种），特别是使用demo，用起来真的很简单。

**Comment by xianjiajun** [comment]
一般来说先看使用说明书，照着实现，理解流程，再看demo，但是按照你的说明书来，dependencies 都写到最后面了，然后又找不到basequickadapter类，基本上就放弃了。建议下面这样，就写得很清楚，照着他的步骤就可以实现，https://github.com/drakeet/MultiType

**Comment by crazysunj** [comment]
好吧，确实考虑不周，我一开始提到了BRVAH，以为大家都知道，文档已经更新，在最下面给出了依赖。

**Comment by crazysunj** [comment]
多谢你给出的建议！

**Comment by xianjiajun** [comment]
使用说明还是要写的小白文一些，只有使用方便了，才会有兴趣查看源码。不客气哈，还是作者你辛苦些。
