### ISSUE TITLE
加油

### ISSUE THREAD

**Issue by Ordosbxy** [crazysunj/MultiTypeRecyclerViewAdapter#5]
一看就是做实际项目中总结出来的， 文档在完善些就好了。
以下这些依赖哪些是必须加的，哪些又是可选择的？ 能说明以下吗？

    compile project(libs.MTRVA_File)
    compile project(libs.MTRVA_File_Anno)
    annotationProcessor project(libs.MTRVA_File_Compiler)
    compile libs.MTRVA_Anno
    compile libs.MTRVA
    apt libs.MTRVA_Compiler

**Comment by crazysunj** [comment]
你好，这个文档上都有哦，http://crazysunj.com/2017/08/14/MTRVA%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E%E4%B9%A6/，你这个应该是最新的，马上要更新2.0.0，代码已经提交了只是还没发布jcenter。

**Comment by Ordosbxy** [comment]
好的，好的。期待2.0.0，计划什么时候发布。这两天正重新改造公司App复杂首页，看了一圈资料，想用MTRVA。

**Comment by crazysunj** [comment]
争取在清明节之前，包括发布，版本升级点以及文档更新等，这样也有时间在清明节集成，碰到问题可以问我，加班也得完成它！

**Comment by Ordosbxy** [comment]
ok，时间赶得上， 那就坐等2.0了，直接用新版本。

**Comment by crazysunj** [comment]
哥们已经全部完成啦，觉得好用的话帮忙点个star分享一下，谢谢啦！遇到问题可以加我QQ387953660。

**Comment by tianshaokai** [comment]
和这个BRVAH有什么联系呢

**Comment by crazysunj** [comment]
跟BRVAH毫无关系，因为BRVAH在相同类型库中处于领先，因此以它为例子进行了讲解如何和自己的Adapter配合，MTRVA是可以和大多数Adapter进行配合的，尽量不让你改动代码。
