### ISSUE TITLE
被README和仓库大小吓走了

### ISSUE THREAD

**Issue by wittyneko** [crazysunj/MultiTypeRecyclerViewAdapter#8]
仓库170M了无法想象没代理的人怎么clone的；
README 太简单了没有效果预览；
功能又强大到让人害怕稳定性；

**Comment by crazysunj** [comment]
你好，大小是不是看错了？而且不用clone全部，最近一次提交就行了，readme只是介绍而已，下面有文档的哦！如果有什么问题加我QQ387953660。
