### ISSUE TITLE
看了圈感觉还有点晕

### ISSUE THREAD

**Issue by yihuajia** [crazysunj/MultiTypeRecyclerViewAdapter#9]
entity必须得实现MultiHeaderEntity或者MultiTypeEntity？那就加个BaseEntity来实现，那么什么时候用MultiHeaderEntity？什么时候用MultiTypeEntity？以及entity中得指定id?之前一直是在用vlayout，但是局部刷新不好使。想看着作者的demo来移植到项目中，感觉还是蛋疼啊

**Comment by crazysunj** [comment]
你好，可以查看下继承关系，哪些是demo里面的东西，哪些是库里面的东西。也可以查看我的开源项目crazydaily，有具体运用。

**Comment by crazysunj** [comment]
很多demo里面的东西是对库的扩展，不想太多无关的代码放在库里面

**Comment by yihuajia** [comment]
就是看得有点晕啊，都快看不下去了。就是看到最早的那个是在diff里面用到了。主要还是不知道MultiHeaderEntity跟MultiTypeEntity的使用时机。需要显示分组的时候就用Header?还有那个id，必须得返回？

**Comment by crazysunj** [comment]
如果直接看代码有点晕，可以配合运行demo去理解，MultiHeaderEntity是用于粘性头的，而MultiTypeEntity是最基础的接口。id并不是必须返回，是用于diffutil的，可以自己自定义，默认是取id才区分的，MTRVA是有文档的哦，http://crazysunj.com/2017/08/14/MTRVA%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E%E4%B9%A6/

**Comment by yihuajia** [comment]
恩恩，，看过文档了。然后看提供的demo还有另外一个sample，都有在entity里面处理id。不过也行吧，省得重载hashcode equals。本来想着再封装一层，毕竟每次写一个helper 还有一个adpater有点烦。那看来只能是在基类里面直接用MultiHeaderEntity了

**Comment by crazysunj** [comment]
所以简单点的，可以直接用注解，这个库重点是对数据的处理，跟UI没有关系，所以可以配合很多Adapter，比如很多老项目都是已经封装了的Adapter，并不影响

**Comment by yihuajia** [comment]
我再看看吧，谢谢了

**Comment by yihuajia** [comment]
大兄弟，出不来Loading的效果，是哪步导致的呢

**Comment by crazysunj** [comment]
大兄弟，麻烦你仔细看一下demo，对应看每个效果，demo是怎么写的？是不是忘了注册loading的adapter呢？

**Comment by yihuajia** [comment]
都有注册啊，就差单步调试demo了

**Comment by yihuajia** [comment]
被type搞死

**Comment by crazysunj** [comment]
你可以仔细阅读一下文档，我觉得对你帮助比较大，最后的注意事项，很清楚的罗列了type的规则！大多数的同学都是一遍过，使用很容易，很简单！

**Comment by yihuajia** [comment]
最后还是跟了遍源码跟出来的，因为这次是重构，所以在考虑要不要用Tangram-Android

**Comment by yihuajia** [comment]
还有个问题想请教下，因为之前项目已经存在一个BaseViewHolder，同时使用的是butternife注解。然后想继续使用butternife的话怎么处理比较好，目前是通过判断viewtype去处理的

**Comment by crazysunj** [comment]
RecyclerView的机制是一个type对应一个布局，而Android的机制是一个view可以找它的子View，适合自己的是最好的！加油！
